Updated Events with new Graphics
ieeeuoft/IEEE-main-site pull request #53
Opened 2022-09-09 03:34 UTC by Mustaballer

Currently missing graphic for React Workshop with updated date.

2022-09-09 21:16 UTC, YuYing-Liang requested changes
Could you put all the events on the slideshow to be in chronological order from left to right
Could you put the deadline for FYA recruitment (Sept. 19th @ 11:59PM)
Unrelated: could you change the email address in the footer from uoft@ieee.org to general@ieee.utoronto.ca

2022-09-09 23:30 UTC, Mustaballer reviewed
For the React Graphic, I'm still waiting for Marketing team to give me an updated graphic so for now I will focus on the other changes

2022-09-12 01:01 UTC, YuYing-Liang commented
@Mustaballer looks good, could you change "Our Sponsors" to "Our Past Sponsors"

2022-09-12 02:23 UTC, YuYing-Liang commented on src/Components/Home/Sponsors/Sponsors.js
> +            <h2 className={styles.sponsorsDivHeading}>Past Sponsors</h2>
Could this be "Our Past Sponsors"

2022-09-12 02:26 UTC, YuYing-Liang approved these changes

2022-09-12 02:28 UTC, merged