Modified Last Years Highlights
ieeeuoft/IEEE-main-site pull request #84
Opened 2024-09-08 19:31 UTC by sarvaSanjay

> Ticket: https://app.clickup.com/t/86b1wk6hn
Updated with latest events and their links.
Also could you specify a date for HTSL? Not mentioned in ticket.

2024-09-09 03:27 UTC, li-ruihao requested changes

2024-09-09 03:27 UTC, li-ruihao commented on src/Assets/Lists/allEvents.js
> +        EventName: "NewHacks 2024",
For this, delete the _NewHacks 2024.jpg_ under /src/Assets/Images/events, and use the one from 2023, we don't need a duplicate one.

2024-09-09 03:27 UTC, li-ruihao commented on src/Assets/Images/events/NewHacks 2024.jpg
please delete this file.

2024-09-09 03:27 UTC, li-ruihao commented on package-lock.json
please do not commit this file, uncommit this file please, thanks

2024-09-10 12:43 UTC, sarvaSanjay commented on src/Assets/Images/events/NewHacks 2024.jpg
I don't quite think that's feasible. Every event's image at least for now is mapped by event name. I would rather suggest deleting the older images.

2024-09-16 03:16 UTC, li-ruihao commented on src/Assets/Images/events/NewHacks 2024.jpg
I see, yea then leaving it there is fine, however let's not delete previous year images

2024-09-25 05:19 UTC, li-ruihao approved these changes

2024-09-25 05:19 UTC, merged