Update External Relations & Marketing Team Pages
ieeeuoft/IEEE-main-site pull request #90
Opened 2024-09-16 06:20 UTC by leoyin1127

Add pictures and member information in member.js

2024-09-16 17:09 UTC, HACKERALERT commented
I think you should revert package-lock.json, it shouldn't be changed.

2024-09-16 17:10 UTC, HACKERALERT commented on src/Assets/Lists/members.js
> +                    position: "Director",
should director be moved up to below the other director?

2024-09-16 17:11 UTC, HACKERALERT commented
Compress images to < 1MB each. Either size dowon or use tinyjpg.

2024-09-16 22:09 UTC, li-ruihao commented on src/Assets/Lists/members.js
> +                    emaileLink: "zoey.xie@mail.utoronto.ca",
Please fix this typo
```suggestion
                    emailLink: "zoey.xie@mail.utoronto.ca",
```

2024-09-17 05:36 UTC, li-ruihao commented on package-lock.json
Please do not commit this file

2024-09-17 05:36 UTC, li-ruihao commented on yarn.lock
Please do not commit this file

2024-09-18 04:31 UTC, leoyin1127 commented
all comments have been resolved; please review again if available, thanks

2024-09-21 02:23 UTC, li-ruihao commented on src/Assets/Lists/members.js
> +                    fullName: "Archana Rajendran",
```suggestion
                    fullName: "Archana Reajendran",
```

2024-09-21 02:24 UTC, li-ruihao commented on src/Assets/Lists/members.js
> +                    fullName: "Chu Qiao",
```suggestion
                    fullName: "Jocelyn Qiao",
```

2024-09-21 02:24 UTC, li-ruihao commented on src/Assets/Lists/members.js
> +                    position: "Director",
```suggestion
                    position: "External Relations Director",
```

2024-09-21 02:25 UTC, li-ruihao commented on src/Assets/Lists/members.js
> +                    position: "Director",
```suggestion
                    position: "External Relations Director",
```

2024-09-21 02:25 UTC, li-ruihao commented on src/Assets/Lists/members.js
> +                    fullName: "Dooyeon Yeom",
```suggestion
                    fullName: "Dunny Yeom",
```

2024-09-21 02:28 UTC, li-ruihao commented on src/Assets/Lists/members.js
> +                    fullName: "Victoria Chen",
Is she in the team??? How come I don't see her anywhere whether it is in org chart or anything? Let me confirm

2024-09-21 02:28 UTC, li-ruihao commented on src/Assets/Lists/members.js
> +                    position: "Director",
```suggestion
                    position: "Marketing Director",
```

2024-09-21 02:28 UTC, li-ruihao commented on src/Assets/Lists/members.js
> +                    position: "Director",
```suggestion
                    position: "Marketing Director",
```

2024-09-21 02:31 UTC, li-ruihao commented on src/Assets/Lists/members.js
> +                    position: "Associate",
```suggestion
                    position: "Senior Associate",
```

2024-09-21 02:31 UTC, li-ruihao commented on src/Assets/Lists/members.js
> +                    position: "Senior Associate",
Please put all senior associates ahead of associates, thanks.

2024-09-21 02:32 UTC, li-ruihao commented on src/Assets/Lists/members.js
> +                    fullName: "Yunxiang Xu",
```suggestion
                    fullName: "David Xu",
```

2024-09-21 02:32 UTC, li-ruihao requested changes
I've done the review for the first time, please make the changes asap, thanks

2024-09-21 03:06 UTC, li-ruihao commented on src/Assets/Lists/members.js
> +                    fullName: "Victoria Chen",
OK confirmed she is in the team. Also, there is a new ER member that needs to be added, her name is Melissa Cao and you can use her Slack Profile Picture, ignore linkedIn and email for now.

2024-09-21 04:46 UTC, leoyin1127 commented
i've finished all the changes required, please review again

2024-09-22 05:47 UTC, li-ruihao approved these changes

2024-09-22 05:47 UTC, merged